# Generated by Django 5.0.7 on 2024-08-12 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_all_posts_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_posts',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.author'),
        ),
        migrations.AlterField(
            model_name='all_posts',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
