# Generated by Django 5.0.7 on 2024-08-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_all_posts_author_alter_all_posts_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_posts',
            name='image_name',
        ),
        migrations.AddField(
            model_name='all_posts',
            name='image',
            field=models.ImageField(default='images/coding.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='all_posts',
            name='tag',
            field=models.ManyToManyField(to='blog.tag'),
        ),
    ]
